
#To edit and compare internal_properties, use WINDEV integrated tools.
#Internal properties refer to the properties of controls in windows, reports, etc.
info :
 name : ProjetDemo_GestionCommerciale
 major_version : 26
 minor_version : 0
 type : 4097
 description : ""
 subtype : 0
project :
 identifier : 0x0
 internal_properties : BgAAAAYAAAC+N5AB+d3GhvP1/NRVeoc1BsHgymYdZFkNaSRhe05Wv0kzyO+J14PHDK2o8u4/CcY2uVmMfUTnmPBd9gVU1tcbNJ5cHJYdKx4kuh/2+/lWD2M+OHq2kDp/r5lFY4QUACU/qFDiE8TshE59/P3WffgNjVvPE5h6q7maUn7GVgVymnHBpUhKQ5maJ682ylQwZCOpPpRe4lMJzqdE+d+9QGhG78DV6Hgr/6V3aRcCZSzUUe64r/XoRdfo4PloD5Qo8/AkCb6M0flfVXmB6OBSICSnGzRgnvDq8eE6iCro5JWnlCyKtYonUHEsoDXfdaWrhn4iKuCr4F/obAezsTBf2qcC2mFnTBK80bXKJkXj9K4Q85sEuz0xW3NZxbX4ryz25QayHZGDnhZ3QKM3NM63KGtxAXf2KHCsiwgpr8TZ/xcHi/awoveChxI9v9PYe7Sg98eGM95yVpvXurEml/kEPRpoq6jOSmn/qfkaiNzFlJT3dTKva8/XM0AHL7M2le+qI5x8lUpQKO9kGajrnSPD1RsKoTLQchp3JRc/EfhYjH0U8JDWTIKFQ25ok7O1axdlTFGr3mwl99vnQIN2uESgvcGcrVTEwztXHTcIOnXd/XHTwt8WrTV017baaV+QNYb+tN6b/IC06f+KR4e4QLHnrARHdIW+aj8gU+lEi/gOmmpd4SN30nIoUvl08Wxbp3HDew+LR9rDodvV8EFnqhK6RnJi6P7TvEEbIwSpkTZyJzhX+0SiTdkHKbNkNLqYFA4qrG9gbwVUSoo4D5n3tAJELt2AvPA0lPHgbUu7UNAs8KoPiTH5CfXT62tziNFue7JZahCQeRT+oaLQ3hlRkW9kSg4TMy2CAyjOobywz9p1cpjyGDPtn8Q4BKMg1rU7p8m/YS0pTJw8dViEYozu31Yx21QmJpCWH8gxATdbARDKiK9g/f0YO/vlJ0xP9HU5NGWyu5T/esvBFVUA39504PObk9azpc8qhNudr6xjQaV7fhqe3pn0cq3YdJMxQ45VLsNjytD57lxCmlYa1Z+FlSFZJAQFMieiUypjdVLELNXYov4Ai7hbvExedcDiCP/6Xu5oNjIx4jesbZa6s8Ffw8MeuanuvjBoANPLPAUolO+CG02j48dJwZweeBHk+agCGx8N4DvtnTQTDbiGAoOwmcaEDmU1xI3mYb84WN2UneSZw7MX93srHcU+wGBiJRwcWFUIDmvkW4jnMMRowuhOBdN7iiV+ZWnpcgXFT3JxQ9/BE5palxVQuDBY9s2nT1jQiAk9G4yysbiYPU+DsTXE0WqPs8WBuBzgNlZ9Wp8urY5Cwu8PpsMUNettL3tPbqf5gZsTteKP1lXjv2lL+g7tva4hxESNRmIy0Ejsz56nuuSdfVcD8wTq1I/6XA4JnUwd77Vl1haulYTjqz5Kxy0q7d2wMAohqQ8u3WOvY0pZEkiBuxYeh6ufdd4Og8ZXoGxStquDn1yrSlVGznYgg7aSsg4L0VNYdDUK9ofdele9mlSNGGTN17bL2/RbqaVAokAmHPt8Bkz2sUvLvDJB2HgkaKvSpDqfnCIwvp/nahArSNTsdxca4cw/bIYUs1n6IN0H5PPxwJJe6nndmV3kTjojxCU1g2NApp1DkjIlWaZPwDp6V6cLDNxEAFAQkCxmtHBe8IomnudT30CkzaiImKV9019e8IoRH52SnOhGhx67dirzHWbxXI3xfoB1sCRKyaz0Gtoiejn96So/TPvhZrD1O6pFgulIacLphmJKMiumLBm0/eebDIvVLNcm91QVnq2JM7MZGGjTyyNRDBktPiGZrATt3yWqM74ppOTkdB9umuAPcm29YYYTJIJd02J1oMVZAQMMqmp5FEXTtpe0bfJH5Z9VHnCZg2CPtUkLFaYvj6tsrsdavaPFV1muKVy47PEj7XMfBS0tfFYyau46c8vdGj70zHoYs9Gi4bLhMXVEXVYoj/Ho2HUF5vGvti7gjUa8FCPjSGaNr1R8eoalXMqJWLVANVsQfku5Iw4zqI6AirChI1sZfyhcovoWPC+MsXalcZmy9AXJDyJvl/SMtcKDDJJroStasMZ8UMfalDAUZf3e2fD7hkAktXPiTpdOffKaTA41KNEKfvX5eHQIp31ZjUf6Vs9GXJLXIgwod7h0E3uDTtMA4hqPCDh301eW
 configurations :
  -
    name : Exécutable Windows 32 bits
    internal_properties : BgAAAAYAAAAmtkzeJvPnsYRVoAmRpzR6abFCpNcj9Qc5eR3+JHFQAlH9DLY5ZO7CvgB2S7zyoP7sfKBMtQyn9YlQ60Qk4wzYcbdqu3tteW9ijCsJiIztl4q7Zm0PbizCcz1ztGom6OEbZ415VL5WDF7AX9th1nTtxC31lSKXUxJWMLt8EEyTPkDm7auXjsgtF0JzdVI6GtuZQ0jxu87JYD6nuWtSeexi7SwbV+DL2JFwlU+MDm2RMr++/4/1F/M2yhCAvjNJQ0SHYEPDsabK8jNnHRlxjU6kuzxgAQir3rvCMVa9QHminB+RD/3o8eJkaCQsdWJVhHXq35Zd1vUFMCY2aof729Vn2X4t9ewPHX9WqKZwjQ4HMnOYBBB5P0IzGx1QqxvxU3Cp5YcX+fVlBIPfmVCp3bwNFtAxr4jHyr8ueiDpzZMm8P1gY7nBJhhYnUejmr+1Zx3covgl9ToCRJD2TB6Jz4paGBqftTScNsZ0kVBm74O5IkTD7sYonuAU530eeH/NZ0Gw0LmczzX5q+aDtylZ8F5TKS/TFtZph8AvF9DuPwKZ+IA/Aa1LpkImwCKoEAbY+bqqCIN9ZFa+aFRZJmd4eNtEnK1BD+bOpv7OlSYOlrzi1BthVyM5Wo8ctOnpwr8ISTw5Tleazn2tREY346RDtEfL7Mw2dSWYi2TrI+NadJCQoic0dovAJLMxzSeMsBV6ukJqVoGRs9umXRKDpednjjghLPmAMbK1f1d+JjdquRyczKQtywBf1v/R3u4fG+dlifOkmDXJ5YNWV/c33shrgHGkqg5byzY0V3ytsMtti4aVtKqv6X9CjT/P3C4tBSuEQToomBquKXIZ5IZy9SzQzLd+fhf0yFGNtHOW0RXaCDejr+jz/FdrSYAmgAzYzQcN0gPc2nA6QawXAnm+J0dvFHE68HR+fO5pW1Rh1gGEhvm7p+PSnQHi9W+ZANEQtgTeainJKhG/aH5mosjCxhkcYT3HwAOrMoSxpbhp+vKjSji2LrnY3Y3NwcUYwz1INNxaWeOUJZBSIcNwuy5Tt/+JRPiKlf98NQlJmEDxevKxqxMqr+yTle9kWIlMwaByPEasBcNd2eT/CMU9uuXdsg0CgPGoJfy1Y7XCjPNW5oW2u8pqAqMKb6NgRjgGN51LzVfVYGIII76gf76Kfymf2D1bQVa/jYbjJJjSq36A8Q1iCc0b0lheJRAAAF1ebXbHRDgN8kJupz9pXwmvl/Tt8yOv3bEgaJgBobc/7bRoC9Qz6bwXN8VRyYHw4VdwS7OSABuhtKmSk3oGIQNFhIlbkdgVpOqvr7fra2UeWX8uTYw5ZaRxyg59ZDX+BHS6eRFHjL4XlQjB8y5SxhSGLhpmfbw1ezB8m43a2B4JD1l8saR2zsxuwvgCkxt21VOMTlmlWvHD+BuGS7PyaJS5vd6Qncl0loo6tFHAVCjHRx7P157UYw2r12rkF3LoINhhRNe/Ir5fG0M9KvI5rIhCcgZ9sO0uK/PesHYK5t//0t8scZn7oRHJ9eBd1zn3BLl3/gmQf1afGArTgpJ+rKRCZZDHg/Xfz3CJh8Blumy/axDe1A03OItRtz5te0lJIY1ra0SKliK9+z7Y3Bpem/JdMyzKaDP+Fq/PhGBfiPvz9TUNnA2l+gggjlDRVYk062lpRHmhzg9vsuBfZrtMyk08hl91OTd/WCvajNXSs/Ll2NImZE+COftrsGCrT5vd1z1gObihCBtREKgPUQ2G1ndPx8Gs6CAvS9Fl8NyxRGkFXxUEPZnsoiUvEQGq4ek89GDoB9Zd5wo5uc+1qEkzKtuOVxGWg8791yXdFk1ROPxBFjTb0QYUVOwt4fT7V7fqnmRDfUPrFh3dBK2tuTh6Srv/1ecO8VnsN5mSHLbFX+HRjh075cFGOHJs07AdqFzrAtkwwjPRhqcWIcGMyc0ShxJTOTSdTqz34PSXAE3RelKcHF+6uyLGYEa5qVkp1p8ZHV+V/t56OZp1EAtEQeHMU0S6FwSQqD6NJkiFjVyaKdO+V7Tf5CZGbPZAwCuO+lApVHyG/45AGQa1Wnz8Ks33HNbUbYq5LiSjMPVc2cVwib/Qe7JPrv+cJa4Jk9omvc+bR2dacD+iTkruZ0fJIRscXPNpz13euVBIJtWM58Jp1NTyIg4SThjcgN27tUXtzoNpIE2x2IAS/zxdi+DrngKhMrvjey35T+TxIfHmBevMKk182mU9oeZDodAOHGghUAWFMi6DpMf4zsj4aEBYtYuJX31b1PYhhNe3Kx/vPGZYvMrXFv3M2p80j1cy0AByQ7R+6E8WJcPNIdTc3Alh1o37drKbfAIYiIEACBRXw3n8aj31VINJ45JCuIvswnR1WxoaYhSlb31KUZT08zJBWy9qAMFJsvYmXFyBKEK39L2MdKO7vZe4ScRir22LxmW6cgDTNdThpa6PLw6e6XrjPEahzXBQRJZ9UafMgVybmlWnDwU3G+uUzVBfg8vWKJ190riLb7N+BjASmty1TFDMGDfJHI/ZjnoBs2HFxSmxenTquz74RU+I5eOVX7+9RFkO1PJ33FizrYXvNQ0t4Y2z7BGmzlpyYCvR5E6Jn70n4L8/ciGCF9e+hxUjGoY2KNvXPpK9yYsB49W5fZPYOtBaCt6rWQ+el622sp413mhd6Qs76p8apCMLTjpRkYoJRWHtDa5X9r2u7Y340xgfnixT692+2KIC6xgkPU6u2AsyRE5NVuT3E+KDbViUFiD0zDAcn2DcfHlCd3Nt28gNsX8ZxaD+F7xS2HHgp5sUotZfkBv9JFNJzB06/lfmvxKkL1OGscUADPbhAcnJBHUWvXjKBzbqPbJAvW7Zjtjx92RNN5/GN05+gwNvtSgER152o8V3cZGG4MIs7L5RHw7gU+685o3VdESSbS5PBy2r5e4jkoPIDZgZFrf7NWig0TaYfrUrnPwv190vBKJ80kfUZhYojQUKiXvNOgUVUgqV4nbYqMjToodtfmjZx6G3FRq4t2LAihplRiEBQr4H39SE4pl65fm86/k94shfJmeQ55L6i/A7xpD+j1j0tIWsuivwDTnpEqPC/lk4dc/fy3vPGThCF9tKlTzTFHiVDPu080HO4EYg7V2xvHIJM1lKG6C5QkCN0mGQMnhvfJtzscd+4GZGwOnKuVNGJX+o+4wboL52sLcLkBnUKS4OWP6G10Prek36XSUSwJEuv9mDASQJx3BEbi+YV5jL+hQdIDuYk0TeiP2E/0OTjBQbZQuud0Nu95/HSsrF1Vzqc5xNZx7o9qX1JVaFdIv2OUPcV3z3TO86/OeXxGEP2muvAyy3WMDXiLDAQ8CGCLmxKsrx21AZhVccRhaJQASsocul16XMry/fA4NjckZdeIOAHnMV/jdNtEKmQcxVpaNak+6WZlXOpm+BiVw3JlPSv1vV6KFPnL5XG3lB5OsqfYkRv9BTFKWQneeU7J1/v/MT8IthaxfMAmEm8kicC7yGJc1LZk13npQ7j4B5pB6llqTsku9YobYi/Y3kp9fKDDlUQVqVN1z4dqTmuoMEk6E3hB03WpD8P4eZ5WBozfPy20t2OEeJlo07qG/c94C01ht/9A/mrp7v4Yk58yjXVne1Rlb5DLpBZPJ/q5t5Xmx0ocjZL00Ob0eqBzHitdzdkUPCq/KGxnDyAmy6lrClTL1i+Yb3cjgHNBzyDHlWSEZU+cH3PxzZjjo7+sHpHGQHl3osAW1npdBdlYQFG2KWzcW6F2ezHmm27UfVQSGWXaFi9SAaHHcBat3H4qpduE8OHOTK474qIr21U4Pdk0p91DJNLkj8RM437Fgnkx/wQ+v9OsNOXLqgmQI3WudOkX4NRStZ4j7wrJmcyE1UuICA17C1xKKAw/0dtvt5NS37SMT7FDxTc9vASQhO7d7aRUqxJW7HXArmTtLRlUGHOWcJIKP2RUz20Q+8VwZnMySFQMfIV4I3JwurHKv1kmM0R7ypcf4f7BpDSWQ6uqcq9kg6qaCIhxSCtVhEb2wURiqjarg8Zc5YQutO5kCEPQlVCHdWdM2r6LESArDN00Fd0ao8ezpabxnXqgXOp9aBxav2Bb9UR0laJM4WN4XssdQ77hL8ngjF6gHYdKgERChAqC3rWm3nBh/mqRWN/jGFsS6+j30TGua7b0C2+8QnWCuGkeVT6+cTCBScADEEgDgKhzF9JGTvPF6sVqy0oYsZ/eqx+Oyu7vFUuhw+01baRw5HaukPq8kGN0LUuN7mDveTf99aoedt4A/9a+s9flC+OFhUkVqhMpqeIvAaLBrjqGwzRrKMzlLsUb7py6l95dPqtiOBoOVQo86W4bYaM/7JRVxQUweJUb0SGGGXYNYem2Ux1LuBojkUAeyjPezNPInSDm43jgKomuRT/qmV2MNicT++7JiGK/co42UeO+smXWSX9ZuH746I9fO2/rCXl8fjaTpaVHW3zyYGnMUF1Y9MbjZBoV1firRN7LcAEfMKkEYOLaoX7w+/VCZvnUphx4bqSoVZk8MMgIWluAAC4XqstswSGdlkp8dQ47nbRIFcTw71mGenDxHCQ5E66qcwwg/NlD64Vze73rnD5vCOjzR8Bm91iwLTywZyU+8bYB4QP4k8CvM6oPYPfAW9R/AW1lzBl0vca5uqM81xTHv7yGfeaE2AKrsixry4Y6czn8Jvio/nybCiGB79fpvAYatFsHMb9rAHvs48dZM9wOYAKnm6JDK2mkZhyqtpgkWY9Xzid29FS4N+cGs2Ir7q5wWXNGBS0JjaYThvM0LpxPMXVEp9evn0ARVAo6DcgNC/lAKy9x2Ym+J6BFDGYuSo2czpVZMaxbVEXiuBG1VUgpDBV9iVaiGfLnysRO6Kww3GPnJYCh1exJj7NC1eUh2Nr2e3YZWdoZgk7sPGTuvV2xI9LfIsy96IiqBT/n0hyVknrLINQp1gBvBPcMWuN06/rRwjKHYbtBUH/t9C+8FcSpUYSlfYIrHPAQfJH13kssrEddiJjPCkJ1HfsLb2N7JCb0ypp622PgERG/HvjRARB/Aj0rQQt/hWFBePg8H/0+TGk6Ur7ST+HD1vX1W1tpj93EtO0SxuBo56HC7ogG6vHUdtGxSq4bvG3CvNUiCMMXN1CjSxulr2zA0+bUT8ka/XcljHgYJ5N6Cu0JMN2fjzyR9ezFXtcsrF7oqpZ0adyt/DmIqYxHfqYN0yJKMVztF4ZMURdzB0RNBl88pEektHKqpHhg5gn3zCY8xo5bbCsv2JTGRR4jRkqlUCWUCMifnlF/VwsFZUFD2I/6ddfIxCsatvMs/dJbG20ulqasiuPR99ehUyE/8TchEIUmOskfn1xdd3M54OaOyV/tGHujHy95M1RuDa/GNdocB6vQ==
    configuration_id : 12006475617066753289
    type : 1
    generation_name : WD Gestion Commerciale.exe
    version :
     major_version : 26
     minor_version : 100
     internal_generation_version : 3
     autoincrement_version : false
    icon_filename : .\description.ico
    language : 1
    new_features_help :
     name : ""
     internal_properties : BgAAAAYAAABCqsp2S46R1loT3djjxKtMJKo7SHO4OR44wp0giifaXEXsXwtCdY/3fnLrtMApXuWkdF4t15CVi42n
 elements :
  identifier : 0x46654c5000031b64
  elements :
   -
     name : MDLC_Ruban
     identifier : 0x46655c0801c683ba
     internal_properties : BgAAAAYAAABj31tPfCmBmqcKNXkJUXdUb2427tbfI+qhpTeJBzhaRr4WotH2y13nBDymEpJOKp5m7g==
     physical_name : .\MDLC_Ruban.wdt
     type : 20
   -
     name : FI_NouveauVolet
     identifier : 0x4665662501ba04d3
     internal_properties : BgAAAAYAAAAUcny4B3w0N4IlVq0c8P9MKK8nP5eQiiqhXX95Qc5GikqUX6UE/Vh+71dBv0e5QbcBAQ==
     physical_name : .\FI_NouveauVolet.wdw
     type : 8
   -
     name : COL_GestionClient
     identifier : 0x466562d5023f14e0
     internal_properties : BgAAAAYAAADYtoCcK1DYg07hLoHZcQ3jqCmnP5GSBKW8UUa6AA8Fyw3VL+VFhQC6KxONayulXVO9RQ==
     physical_name : .\COL_GestionClient.wdg
     type : 7
   -
     name : COL_Notification
     identifier : 0x46655c0901e387d1
     internal_properties : BgAAAAYAAAALB3MXlNFZAs9inaIh7rVxi+TGlhwtC260W6ba1in1A+HfjHtlpDU/rJQO6qom0sYOFg==
     physical_name : .\COL_Notification.wdg
     type : 7
   -
     name : FI_Volet_Fiche_Saisie_Client
     identifier : 0x4665664e01f9a605
     internal_properties : BgAAAAYAAAAqIBJ2tfK65exDCPRyVeWm6Ovnf1Ll6L9O5ylFIsTICMwS8zPFRPqgzXVvSckH8+UvNw==
     physical_name : .\FI_Volet_Fiche_Saisie_Client.wdw
     type : 8
   -
     name : FEN_Onglet
     identifier : 0x4665662501c705ae
     internal_properties : BgAAAAYAAAB/21dLeCWNnqsOMwqpqhMizfy0bHztJyCJ/9nvXcLIaOgIoFVnUrPbCDCqFp5SLqJq6g==
     physical_name : .\FEN_Onglet.wdw
     type : 2
   -
     name : REQ_RechercheClient
     identifier : 0x46659de30129c4e8
     internal_properties : BgAAAAYAAABz3Wkl9tP+bsS4i966QP1VKt4qnG1LqWHuXFIcBiYrHBWwcs2ZBYaXf4l5BinBfmX2
     physical_name : .\REQ_RechercheClient.WDR
     type : 5
   -
     name : REQ_NombreCommandeEtat
     identifier : 0x467834820330559a
     internal_properties : BgAAAAYAAAAuNAYaqdZeEdjy+IrM5K4BSBuHX+UKArNKiAWXKWA8xCCeHMlqmel/eaEb5a0j39E7Ow==
     physical_name : .\REQ_NombreCommandeEtat.WDR
     type : 5
   -
     name : COL_eCommerce
     identifier : 0x46782fbf032ebc50
     internal_properties : BgAAAAYAAAC5leElgv+3uAHr+DTz4ZK0DXhU1Pg5y8aoonMNL+CqHpJuPAAz0M90YtrEPMQ8xDScpA==
     physical_name : .\COL_eCommerce.wdg
     type : 7
   -
     name : REQ_ModeReglement
     identifier : 0x46782f58032c2a94
     internal_properties : BgAAAAYAAAAMCmSwjzR8r7pA3doYrFVhzrEt/cuIWXa2tXHRk+Y20j6shCYFxrJZBz+5B49BOa8ZGQ==
     physical_name : .\REQ_ModeReglement.WDR
     type : 5
   -
     name : REQ_FacturesClient
     identifier : 0x46782bdd0300924b
     internal_properties : BgAAAAYAAACT/clFljPeFuR7roXk+L0bhrgKLrVmgT3w2rwrLxfM844vcdSA5VnfV2lZZkmhHoWW
     physical_name : .\REQ_FacturesClient.WDR
     type : 5
   -
     name : REQ_CommandesClient
     identifier : 0x46782a2102feca07
     internal_properties : BgAAAAYAAABxzan9Snc/cHlTy6Jolz4xmYaMbNUbAU+Ot0/TgTVZn2GjAtgnm+ZcGgL8xEyEfGxU3A==
     physical_name : .\REQ_CommandesClient.WDR
     type : 5
   -
     name : FI_Volet_Fiche_Saisie_Commande
     identifier : 0x468e8abb02a3371e
     internal_properties : BgAAAAYAAADJRTHV0o+nSBEB15gofCsot+auNvXZHbp2AVY8QvSeoqKiWt3He5DyMurULPTslATMVA==
     physical_name : .\FI_Volet_Fiche_Saisie_Commande.wdw
     type : 8
   -
     name : REQ_CommandesSelonEtat
     identifier : 0x4698fb2504a4a024
     internal_properties : BgAAAAYAAAA/GxcLuOXN3uuh3uCqXcqEUS50pJ37y6Z2QezXPUnVwz2Xk530EOUuyHBqVt4S7uIqKg==
     physical_name : .\REQ_CommandesSelonEtat.WDR
     type : 5
   -
     name : WinDevDialogBox
     identifier : 0x4698d2c50234eaf8
     internal_properties : BgAAAAYAAADGTC5yse7G6fD6js1XVOuPzF3Lgyz63blOx//Tp0/NyzX93xsULrcHkYlzTdUL9+nTUw==
     physical_name : .\WinDevDialogBox.WDW
     type : 2
   -
     name : WinDevMessageBox
     identifier : 0x4698d2c50230e8d6
     internal_properties : BgAAAAYAAABt6UVZZtNbBN0XF2o8XXR0s8JqwgoLrAOJnx/hf7DaDj7W3gon01KgfqYQ6KhYIJB4+A==
     physical_name : .\WinDevMessageBox.WDW
     type : 2
   -
     name : FI_Volet_Table_Client
     identifier : 0x469d1f770a1970c4
     internal_properties : BgAAAAYAAAAiGBoOverC3eSjKbmlfwN9FhUttYxv5Pacvnbtvmg0/DTuOrZS+L9gxX1nUdEP690nLw==
     physical_name : .\FI_Volet_Table_Client.wdw
     type : 8
   -
     name : COL_Outils
     identifier : 0x469e110804dca165
     internal_properties : BgAAAAYAAACyiOo+DXoybXR0VYzTjjAWnPnbA9l6+xKMfUREFhnzNZtnIv/caLCpFQ33wUG/uy2Xnw==
     physical_name : .\COL_Outils.wdg
     type : 7
   -
     name : FI_Carte
     identifier : 0x469e3bc305038c3a
     internal_properties : BgAAAAYAAAC1kZ2BPhsTzIWFLJA5OnJ2Db6ImDa38Xh1ZLDIdNs7laNJ9wXzEiE25l5YoGCQaFigoA==
     physical_name : .\FI_Carte.wdw
     type : 8
   -
     name : REQ_ValeurDuneCaractéristique
     identifier : 0x469fae8504e2d847
     internal_properties : BgAAAAYAAAC3gS15eocIGugi6ihI4AnR/ASSHmWg8b1Y0iRpGb0O+cpFnxIGaiYJgacFsp19OqGy
     physical_name : .\REQ_ValeurDuneCaractéristique.WDR
     type : 5
   -
     name : FI_Filtre
     identifier : 0x46a252bf04bdda4d
     internal_properties : BgAAAAYAAAAfe3crmMVtfsur4UpAVDzxA7bSug393JWraDwWbLpYsFyAMxe7AU7QqJAK9r4yzsIKCg==
     physical_name : .\FI_Filtre.wdw
     type : 8
   -
     name : REQ_MaxOrdreAffichageProduit
     identifier : 0x46a65c8c0c6b1607
     internal_properties : BgAAAAYAAAD/WdUxgj/QigCaaQXmjkOXO7pQupC7R7n3X4kH7Mo5LsibZdxIb1YpwV9NalW1Aul6
     physical_name : .\REQ_MaxOrdreAffichageProduit.WDR
     type : 5
   -
     name : FI_Volet_Fiche_Saisie_Produit
     identifier : 0x46a64ef80aea09d4
     internal_properties : BgAAAAYAAABYNgAcq9BYA86iBCYxzMJLWNVXD7QImtRRiFP7Lekr9TPvwcgt5fNzq5MN66sl3dM9xQ==
     physical_name : .\FI_Volet_Fiche_Saisie_Produit.wdw
     type : 8
   -
     name : FEN_ArbreFamillesProduit
     identifier : 0x46a656f60c1e42c0
     internal_properties : BgAAAAYAAACTb8vf7FnRild76a0cESK+H0iqWnBZ/0RNDpZiTtHFW1FPU+8oLFrQ9CyWYiLemg72fg==
     physical_name : .\FEN_ArbreFamillesProduit.wdw
     type : 2
   -
     name : REQ_ListeProduit
     identifier : 0x46a600c1068c80ca
     internal_properties : BgAAAAYAAAA7F2OnBEHp8v/T+3Dyq8b23ZxkfNqVRUKOP7jFR34cJJwUkGApnZSonIR+ejq2QrYeJg==
     physical_name : .\REQ_ListeProduit.WDR
     type : 5
   -
     name : REQ_FamilleProduit
     identifier : 0x46a600c6068e95f8
     internal_properties : BgAAAAYAAAAmLA4Skc5mCdD4EBonwhh1QncRcbUO/0eqoG46ssPRL90B957/z7dNcakT7bUr18kzMw==
     physical_name : .\REQ_FamilleProduit.WDR
     type : 5
   -
     name : FI_Volet_Table_Produit
     identifier : 0x46a89f97026258a6
     internal_properties : BgAAAAYAAAB/21dLeCWNnqtxUsq44wbyMb6EBK17BKdO7Wg/ZaF9W+UPtSM8zil+CDCqFp5SLqJq6g==
     physical_name : .\FI_Volet_Table_Produit.wdw
     type : 8
   -
     name : REQ_LignesCdeDuneCde
     identifier : 0x46ba2414023d70cb
     internal_properties : BgAAAAYAAABo5lBMeyCIk1620iJFq/nGohUBoYTUt8CiZtRIYDbe0iaESxUr1003+yOdG5tVLaNt9Q==
     physical_name : .\REQ_LignesCdeDuneCde.WDR
     type : 5
   -
     name : FI_ChoixCaractéristique
     identifier : 0x46ea95900193d132
     internal_properties : BgAAAAYAAAC6kOImhcJqdXyY2eTgrX5dfH8749ZmMTyrsz8W1lBE5GiWXPWpELDNHQX/+bk3wzWfpw==
     physical_name : .\FI_ChoixCaractéristique.wdw
     type : 8
   -
     name : REQ_RechercheProduit
     identifier : 0x46eab47e023ca16b
     internal_properties : BgAAAAYAAABh3VlNeiePoKm10SP8EXOLp/Cykpcfa4KihtPZAbVhn62zumfCQD62CjKsFJxULJxk7A==
     physical_name : .\REQ_RechercheProduit.WDR
     type : 5
   -
     name : COL_GestionProduit
     identifier : 0x46efd1ed0f452b50
     internal_properties : BgAAAAYAAAAiGBoOverC3eQFF/Pex4xzHAMbMxv8oWCoki+JMf6eGuIsxNdp7g+KxX1nUdEP690nLw==
     physical_name : .\COL_GestionProduit.wdg
     type : 7
   -
     name : ETAT_Clients
     identifier : 0x47bdb8770291772b
     internal_properties : BgAAAAYAAADUsjx4Rzx0d8fH+LNTNUCO5qU9ZcVOmgdIRgm39yj0HNRuuU42jJsRtJcB/4d5AffBQQ==
     physical_name : .\ETAT_Clients.wde
     type : 3
   -
     name : ETAT_Facture
     identifier : 0x47c54054073edefc
     internal_properties : BgAAAAYAAABFwa3xTmtDXG5G4+NbbSiYsfDIEKBpuA60myHnRdo4wDioduhb9JCMO+7o0FCAeGhQ0A==
     physical_name : .\ETAT_Facture.wde
     type : 3
   -
     name : REQ_Facture
     identifier : 0x47c5413107403c60
     internal_properties : BgAAAAYAAADLRzPX1JGZQgAMrsqr/5o8NQBsXAiqOoKuYzPWfxhyZlq2hEj1CnfWcdTOKurmkgbOVg==
     physical_name : .\REQ_Facture.WDR
     type : 5
   -
     name : FI_Volet_Fiche_Saisie_Facture
     identifier : 0x47c5963d019774a7
     internal_properties : BgAAAAYAAAAdeXUplsNrdMbOsfTBavQ5OVYMrJb4QO6fvpc/BuG9a4Wf5p76BzYUs5YA+Lgo0MAICA==
     physical_name : .\FI_Volet_Fiche_Saisie_Facture.wdw
     type : 8
   -
     name : REQ_SaisieAssistéeAjoutProduit
     identifier : 0x4c17d884004ff568
     internal_properties : BgAAAAYAAACLh/OXFFHZgpU0ua2gYitkcdBI0G2UfehS+m9psuqoEOg4coPJd02DMhSOaiqmUkaOlg==
     physical_name : .\REQ_SaisieAssistéeAjoutProduit.WDR
     type : 5
  other_elements : []
  analysis : .\WW_BaseSiteVente.ana\WW_BaseSiteVente.wda
  net_assemblies : []
  uwp_api : []
  external_components : []
  internal_components : []
 report_and_queries_enabled : false
 data_directory : <RepExeOuRepDonneesCommun>
 common_generation_directory : true
 languages :
  - fr-FR
 wb_style_sheet : .\WD Gestion Commerciale.wws
 rad_options :
  internal_properties : BgAAAAYAAADy6g8oABFBh1+QiaAsMK6I2XmPzsUlwgVK5HBJHAopecPZPAzRmrZ+Ebpzy7DY/iSH3vj19WS+YzrlSnKLtidu6f66Wu6JuV3/I/muE15t0v2RirX+50zEIbA78GBF
 code_elements :
  internal_properties : BgAAAAYAAACyo+AGPHs6tl+CMW8i1j+hisKclwORtfzp4tr+6B34gnEg+AegA2o6CeaiNwKFgQlNnqdA
  type_code : 0
  p_codes :
   -
     code : |1-
      CONSTANT
      	CST_TOUTAFFICHER = 1
      	CST_FILTRE = 2
      	CST_TYPECARACTERISTIQUE_COULEUR = 32
      	REP_PHOTOS_PRODUITS = "produits"
      
      	// Renseignez ici votre clé d'API Google Maps (si besoin)
      	CST_CLÉGOOGLE = ""
      FIN
      
      
      // Initialisation de la clé Google
      si PAS CST_CLÉGOOGLE ~= "" ALORS
      	CarteLicenceGgl(CST_CLÉGOOGLE)
      FIN
      // Demande à l'utilisateur s'il souhaite générer des données de test à jour (commandes, factures...)
      //GénérationDonnées()
     type : 196608
   -
     code : |1+
      
      
     type : 196610
   -
     code : |1+
      
      
     type : 196619
   -
     type : 196621
   -
     type : 196627
     enabled : false
 code_parameters :
  internal_properties : BgAAAAYAAAA6ih3UbgNXHwTtiPSFUEj+2fi/m7v4QV2rqidAupM=
rad :
 internal_properties : BgAAAAYAAABhIL0UXeZmxDJxY3Xy0Q==
project_explorer :
 explorer_type : project
 children :
  -
    explorer_type : windows
    children :
     -
       name : Outils
       explorer_type : custom_folder
       children :
        -
          name : FI_Carte
          explorer_type : element
          type : 8
        -
          name : FI_NouveauVolet
          explorer_type : element
          type : 8
        -
          name : WinDevDialogBox
          explorer_type : element
          type : 2
        -
          name : WinDevMessageBox
          explorer_type : element
          type : 2
        -
          name : FI_Filtre
          explorer_type : element
          type : 8
        -
          name : FEN_ArbreFamillesProduit
          explorer_type : element
          type : 2
        -
          name : FI_ChoixCaractéristique
          explorer_type : element
          type : 8
resources :
 string_res :
  identifier : 0x0
  internal_properties : BgAAAAYAAAAnMYFQ1bL/vz9ehh7L22SNNSlIzGTOI8h5F/WtgDNP
custom_note :
 internal_properties : BgAAAAYAAAAd98VSJfHHqE3P0QHwrwdhn7ig8dWBR6valpUTgnAMTVXiDg==
